/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import examen.p2.Paciente;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import storage.PilaPacientes;

/**
 *
 * @author cardonapablo
 */
public class ListPaciente extends javax.swing.JFrame {

    /**
     * Creates new form ListPaciente
     */
    public ListPaciente() {
        initComponents();
    }
    
    Font baseFont = new Font("Helvetica", Font.PLAIN, 24);
    PilaPacientes pacientes;
    Menu menu;
    
    public ListPaciente(PilaPacientes pacientes, Menu menu) {
        setTitle("Pacientes registrados");
        this.menu = menu;
        this.pacientes = pacientes;
        setSize(1000, 1000);
        setLocation(1500, 700);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);
        drawList();
    }
    
    private void drawList() {
        
        JPanel panel = new JPanel();
        panel.setSize(800, 400);
        panel.setLocation(100, 100);
        panel.setVisible(true);
        this.add(panel);
        
        final DefaultListModel model = new DefaultListModel();
        Paciente[] pacientesRaw = this.pacientes.getAllPacientes();
        if(pacientesRaw.length == 0)
            model.addElement("No hay pacientes registrados");
        for (int i = 0; i < pacientesRaw.length; i++) {
            Paciente paciente = pacientesRaw[i];
            String nombreCompleto = paciente.getName();
            nombreCompleto += "    |    ";
            nombreCompleto += Byte.toString(paciente.getEdad());
            nombreCompleto += "    |    ";
            nombreCompleto += paciente.getGenero();
            nombreCompleto += "    |    ";
            nombreCompleto += paciente.getNss();

            model.addElement(nombreCompleto);
        }
        
        JList list = new JList(model);
        list.setFont(baseFont);
        list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        list.setLayoutOrientation(JList.VERTICAL);
        
        JScrollPane listScroller = new JScrollPane(list);
        listScroller.setLocation(0,0);
        listScroller.setPreferredSize(new Dimension(800, 400));
        
        panel.add(listScroller);
        
        JButton regresar = new JButton("Volver");
        regresar.setFont(baseFont);
        regresar.setLocation(100,500);
        regresar.setSize(200, 50);
        regresar.setVisible(true);
        
        regresar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                menu.setVisible(true);
            }
        });
        
        this.add(regresar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
